kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app-sample
  template:
    metadata:
      labels:
        app: java-springboot-app-sample
    spec:
      containers:
        - name: my-java-springboot
          image: java-springboot-image:sample
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc-sample
spec:
  ports:
    - name: http-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: java-springboot-app-sample